<template>
    <div>
        <h3>目錄</h3>
        <div>
            <div>
                <div>
                    <span>冊1</span>
                    <span>冊名</span>
                </div>
                <div>
                    <a>卷1</a>
                </div>

                <div>
                    <span>冊2</span>
                    <span>冊名</span>
                </div>
                <div>
                    <a>卷5</a>
                </div>

                <div>
                    <span>冊3</span>
                    <span>冊名</span>
                </div>
                <div>
                    <a>卷9</a>
                </div>
            </div>
        </div>
    </div>
</template>